apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kajetan7/homelab-apps.git'
    targetRevision: HEAD
    path: infra/crds
    directory:
      include: kube-prometheus-stack-crds.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
