apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-staging-issuer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kajetan7/homelab-apps.git'
    targetRevision: HEAD
    path: infra/crds
    directory:
      include: letsencrypt-staging-issuer.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - name: cert-manager
