# CRDs required for kube-prometheus-stack (Prometheus Operator)
# Source: https://github.com/prometheus-operator/prometheus-operator/tree/main/example/prometheus-operator-crd
#
# This file contains all required CRDs for kube-prometheus-stack in a single YAML file (multi-doc format)

---
# Alertmanager
# (truncated for brevity, use full CRD from official source in production)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Alertmanager
    plural: alertmanagers
    singular: alertmanager
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# AlertmanagerConfig
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerconfigs.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: AlertmanagerConfig
    plural: alertmanagerconfigs
    singular: alertmanagerconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
# PodMonitor
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PodMonitor
    plural: podmonitors
    singular: podmonitor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# Probe
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: probes.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Probe
    plural: probes
    singular: probe
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# Prometheus
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Prometheus
    plural: prometheuses
    singular: prometheus
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# PrometheusAgent
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusagents.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PrometheusAgent
    plural: prometheusagents
    singular: prometheusagent
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
# PrometheusRule
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusrules.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PrometheusRule
    plural: prometheusrules
    singular: prometheusrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# ScrapeConfig
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scrapeconfigs.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: ScrapeConfig
    plural: scrapeconfigs
    singular: scrapeconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
# ServiceMonitor
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: ServiceMonitor
    plural: servicemonitors
    singular: servicemonitor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# ThanosRuler
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: thanosrulers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: ThanosRuler
    plural: thanosrulers
    singular: thanosruler
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
